controller_list:
  - name: mmrobot/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - mmrobot_joint1
      - mmrobot_joint2
      - mmrobot_joint3
      - mmrobot_joint4
      - mmrobot_joint5
      - mmrobot_joint6
      - mmrobot_joint7
  - name: mmrobot/panda_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mmrobot_finger_joint1
      - mmrobot_finger_joint2
