controller_list:
  - name: fake_arm_group_controller
    joints:
      - mmrobot_joint1
      - mmrobot_joint2
      - mmrobot_joint3
      - mmrobot_joint4
      - mmrobot_joint5
      - mmrobot_joint6
      - mmrobot_joint7
  - name: fake_hand_controller
    joints:
      - mmrobot_finger_joint1
      - mmrobot_finger_joint2
  - name: fake_mmrobot_arm_hand_controller
    joints:
      - mmrobot_joint1
      - mmrobot_joint2
      - mmrobot_joint3
      - mmrobot_joint4
      - mmrobot_joint5
      - mmrobot_joint6
      - mmrobot_joint7
      - mmrobot_finger_joint1
      - mmrobot_finger_joint2