#!/usr/bin/env python
import roslib
import rospy

import tf
from nav_msgs.msg import Odometry

def handle_mmrobot_pose(msg, link_name):
    br = tf.TransformBroadcaster()
    p = msg.pose.pose
    br.sendTransform((p.position.x, p.position.y, p.position.z),
                     (p.orientation.x, p.orientation.y, p.orientation.z, p.orientation.w),
                     rospy.Time.now(),
                     link_name,
                     "odom")

if __name__ == '__main__':
    rospy.init_node('base_link_tf_broadcaster')
    link_name = "base_link"
    rospy.Subscriber('/mmrobot/ground_truth_odom',
                     Odometry,
                     handle_mmrobot_pose,
                     link_name)
    rospy.spin()

